# Generated by Django 4.2.4 on 2023-08-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('location_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='row',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_column',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.theater'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('movie', 'theater', 'datetime'), name='unique_movie_theater_datetime'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('seat_row', 'seat_column', 'theater'), name='unique_seat_position'),
        ),
        migrations.DeleteModel(
            name='Row',
        ),
        migrations.AddField(
            model_name='theater',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.branch'),
            preserve_default=False,
        ),
    ]
